name: test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  contents: read

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  prepare-smoke:
    runs-on: ubuntu-latest
    outputs:
      includes: ${{ steps.smoke.outputs.matrix }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v6
      -
        name: Smoke test matrix
        id: smoke
        uses: docker/bake-action/subaction/matrix@v6
        with:
          target: smoke-test
          fields: platforms

  smoke:
    runs-on: ${{ startsWith(matrix.platforms, 'linux/arm') && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    needs:
      - prepare-smoke
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.prepare-smoke.outputs.includes) }}
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      -
        name: Test
        uses: docker/bake-action@v6
        with:
          targets: smoke-test
          set: |
            *.platform=${{ matrix.platforms }}
