name: test

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Test
        uses: docker/bake-action@v4
        with:
          targets: smoke-test
